trigger: 
- main

pool:
  #vmImage: ubuntu-latest
  name: Default

variables:
  buildConfiguration: 'Release'

steps:
- bash: echo hello world
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build --configuration $(buildConfiguration)'